version: '3.4'

services:
 datastore:
    image: mongo
    ports:
      - "27017:27017" 

 userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService\Dockerfile
    depends_on:
      - datastore
    ports:
      - 80
      - "44358:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44319
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=C:\https\UserService.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:C:\https:ro

 tweetservice:
    image: ${DOCKER_REGISTRY-}tweetservice
    build:
      context: .
      dockerfile: TweetService\Dockerfile
    depends_on:
      - datastore
    ports:
      - 80
      - "44319:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44319
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=C:\https\TweetService.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:C:\https:ro 